# (C) Datadog, Inc. 2022-present
# All rights reserved
# Licensed under a 3-clause BSD style license (see LICENSE)

# This file is autogenerated.
# To change this file you should edit assets/configuration/spec.yaml and then run the following commands:
#     ddev -x validate config -s <INTEGRATION_NAME>
#     ddev -x validate models -s <INTEGRATION_NAME>

from datadog_checks.base.utils.models.fields import get_default_field_value


def shared_service(field, value):
    return get_default_field_value(field, value)


def instance_disable_generic_tags(field, value):
    return False


def instance_email_address(field, value):
    return 'email@example.com'


def instance_empty_default_hostname(field, value):
    return False


def instance_enable_activations(field, value):
    return True


def instance_enable_groups(field, value):
    return True


def instance_enable_incidents(field, value):
    return True


def instance_enable_onedrive(field, value):
    return True


def instance_enable_outlook(field, value):
    return True


def instance_enable_sharepoint(field, value):
    return True


def instance_enable_skype(field, value):
    return True


def instance_enable_synthetic_email(field, value):
    return True


def instance_enable_synthetics(field, value):
    return True


def instance_enable_teams(field, value):
    return True


def instance_enable_yammer(field, value):
    return True


def instance_metric_patterns(field, value):
    return get_default_field_value(field, value)


def instance_onedrive_file_size(field, value):
    return 4000000


def instance_outlook_mailbox_topn(field, value):
    return 0


def instance_password(field, value):
    return get_default_field_value(field, value)


def instance_probe_mode(field, value):
    return True


def instance_service(field, value):
    return get_default_field_value(field, value)


def instance_sharepoint_sites(field, value):
    return get_default_field_value(field, value)


def instance_tags(field, value):
    return get_default_field_value(field, value)


def instance_username(field, value):
    return 'user@example.com'
