# Copyright (C) 2023 Crest Data Systems.
# All rights reserved

EVENTS_CONFIG = [
    {
        "type": "audit",
        "dashboard_panels": {
            "audit_details": {
                "type": "log",
                "event_fields": [
                    "_id",
                    "audit_log_event",
                    "severity_level",
                    "supporting_data.data_type",
                    "user",
                    "organization_unit",
                    "type",
                    "timestamp",
                ],
                "alias_fields": {
                    "cds-netskope-audit-id": ["_id"],
                    "cds-netskope-event-type": ["audit_log_event"],
                    "cds-netskope-severity-level": ["severity_level"],
                    "cds-netskope-data-type": ["supporting_data.data_type"],
                    "cds-netskope-user": ["user"],
                    "cds-netskope-organization-unit": ["organization_unit"],
                    "cds-netskope-log-type": ["type"],
                    "timestamp": [],
                },
                "tag_fields": ["cds-netskope-audit-id"],
                "log_fields": [
                    "cds-netskope-audit-id",
                    "cds-netskope-event-type",
                    "cds-netskope-severity-level",
                    "cds-netskope-data-type",
                    "cds-netskope-user",
                    "cds-netskope-organization-unit",
                    "cds-netskope-log-type",
                    "timestamp",
                ],
                "timestamp_field": "timestamp",
            }
        },
    },
    {
        "type": "application",
        "dashboard_panels": {
            "application_details": {
                "type": "log",
                "event_fields": [
                    "_id",
                    "ccl",
                    "device",
                    "device_classification",
                    "browser",
                    "activity",
                    "user",
                    "app",
                    "access_method",
                    "os",
                    "category",
                    "timestamp",
                ],
                "alias_fields": {
                    "cds-netskope-application-id": ["_id"],
                    "cds-netskope-ccl": ["ccl"],
                    "cds-netskope-device": ["device"],
                    "cds-netskope-device-classification": ["device_classification"],
                    "cds-netskope-browser": ["browser"],
                    "cds-netskope-activity": ["activity"],
                    "cds-netskope-user": ["user"],
                    "cds-netskope-app": ["app"],
                    "cds-netskope-access-method": ["access_method"],
                    "cds-netskope-os": ["os"],
                    "cds-netskope-category": ["category"],
                    "timestamp": [],
                },
                "tag_fields": ["cds-netskope-application-id"],
                "log_fields": [
                    "cds-netskope-application-id",
                    "cds-netskope-ccl",
                    "cds-netskope-device",
                    "cds-netskope-device-classification",
                    "cds-netskope-browser",
                    "cds-netskope-activity",
                    "cds-netskope-user",
                    "cds-netskope-app",
                    "cds-netskope-access-method",
                    "cds-netskope-os",
                    "cds-netskope-category",
                    "timestamp",
                ],
                "timestamp_field": "timestamp",
            },
            "application.bytes_transferred": {
                "type": "metric",
                "event_fields": ["_id", "client_bytes", "server_bytes", "user", "app", "timestamp"],
                "alias_fields": {
                    "application-id": ["_id"],
                    "client_bytes": [],
                    "server_bytes": [],
                    "user": [],
                    "app": [],
                    "timestamp": ["timestamp"],
                },
                "tag_fields": ["application-id", "user", "app"],
                "metric_fields": ["client_bytes", "server_bytes"],
                "timestamp_field": "timestamp",
            },
        },
    },
    {
        "type": "alert",
        "dashboard_panels": {
            "alert_details": {
                "type": "log",
                "event_fields": [
                    "_id",
                    "userip",
                    "access_method",
                    "app",
                    "appcategory",
                    "traffic_type",
                    "activity",
                    "alert_type",
                    "alert_name",
                    "policy",
                    "dlp_rule",
                    "dlp_profile",
                    "dlp_severity",
                    "dlp_file",
                    "file_size",
                    "file_type",
                    "dlp_rule_severity",
                    "action",
                    "acked",
                    "breach_target_references",
                    "malsite_category",
                    "severity_level",
                    "user",
                    "timestamp",
                ],
                "alias_fields": {
                    "cds-netskope-alert-id": ["_id"],
                    "cds-netskope-user-ip": ["userip"],
                    "cds-netskope-access-method": ["access_method"],
                    "cds-netskope-app": ["app"],
                    "cds-netskope-app-category": ["appcategory"],
                    "cds-netskope-traffic-type": ["traffic_type"],
                    "cds-netskope-activity": ["activity"],
                    "cds-netskope-alert-type": ["alert_type"],
                    "cds-netskope-alert-name": ["alert_name"],
                    "cds-netskope-policy": ["policy"],
                    "cds-netskope-dlp-rule": ["dlp_rule"],
                    "cds-netskope-dlp-profile": ["dlp_profile"],
                    "cds-netskope-dlp-severity": ["dlp_severity"],
                    "cds-netskope-dlp-file": ["dlp_file"],
                    "cds-netskope-file-size": ["file_size"],
                    "cds-netskope-file-type": ["file_type"],
                    "cds-netskope-dlp-rule-severity": ["dlp_rule_severity"],
                    "cds-netskope-action": ["action"],
                    "cds-netskope-acked": ["acked"],
                    "cds-netskope-breach-target-references": ["breach_target_references"],
                    "cds-netskope-malsite-category": ["malsite_category"],
                    "cds-netskope-severity-level": ["severity_level"],
                    "cds-netskope-user": ["user"],
                    "timestamp": [],
                },
                "tag_fields": ["cds-netskope-alert-id"],
                "log_fields": [
                    "cds-netskope-alert-id",
                    "cds-netskope-user-ip",
                    "cds-netskope-access-method",
                    "cds-netskope-app",
                    "cds-netskope-app-category",
                    "cds-netskope-traffic-type",
                    "cds-netskope-activity",
                    "cds-netskope-alert-type",
                    "cds-netskope-alert-name",
                    "cds-netskope-policy",
                    "cds-netskope-dlp-rule",
                    "cds-netskope-dlp-profile",
                    "cds-netskope-dlp-severity",
                    "cds-netskope-dlp-file",
                    "cds-netskope-file-size",
                    "cds-netskope-file-type",
                    "cds-netskope-dlp-rule-severity",
                    "cds-netskope-action",
                    "cds-netskope-acked",
                    "cds-netskope-breach-target-references",
                    "cds-netskope-malsite-category",
                    "cds-netskope-severity-level",
                    "cds-netskope-user",
                    "timestamp",
                ],
                "timestamp_field": "timestamp",
            }
        },
    },
    {
        "type": "connection",
        "dashboard_panels": {
            "connection_details": {
                "type": "log",
                "event_fields": [
                    "_id",
                    "client_bytes",
                    "conn_duration",
                    "conn_endtime",
                    "conn_starttime",
                    "count",
                    "http_transaction_count",
                    "numbytes",
                    "server_bytes",
                    "access_method",
                    "app",
                    "appcategory",
                    "browser",
                    "browser_version",
                    "bypass_traffic",
                    "device",
                    "domain",
                    "dst_country",
                    "dst_location",
                    "dst_region",
                    "dst_timezone",
                    "dst_zipcode",
                    "dstip",
                    "dstport",
                    "hostname",
                    "organization_unit",
                    "os",
                    "os_version",
                    "page",
                    "protocol",
                    "site",
                    "src_country",
                    "src_location",
                    "src_region",
                    "src_time",
                    "src_timezone",
                    "src_zipcode",
                    "srcip",
                    "traffic_type",
                    "type",
                    "ur_normalized",
                    "url",
                    "user",
                    "userip",
                    "ccl",
                    "user_generated",
                    "timestamp",
                ],
                "alias_fields": {
                    "cds-netskope-connection-id": ["_id"],
                    "cds-netskope-client-bytes": ["client_bytes"],
                    "cds-netskope-connection-duration": ["conn_duration"],
                    "cds-netskope-connection-endtime": ["conn_endtime"],
                    "cds-netskope-connection-starttime": ["conn_starttime"],
                    "cds-netskope-count": ["count"],
                    "cds-netskope-http-transactions": ["http_transaction_count"],
                    "cds-netskope-bytes": ["numbytes"],
                    "cds-netskope-server-bytes": ["server_bytes"],
                    "cds-netskope-access-method": ["access_method"],
                    "cds-netskope-app": ["app"],
                    "cds-netskope-app-category": ["appcategory"],
                    "cds-netskope-browser": ["browser"],
                    "cds-netskope-browser-version": ["browser_version"],
                    "cds-netskope-bypass-traffic": ["bypass_traffic"],
                    "cds-netskope-device": ["device"],
                    "cds-netskope-domain": ["domain"],
                    "cds-netskope-destination-country": ["dst_country"],
                    "cds-netskope-destination-location": ["dst_location"],
                    "cds-netskope-destination-region": ["dst_region"],
                    "cds-netskope-destination-timezone": ["dst_timezone"],
                    "cds-netskope-destination-zipcode": ["dst_zipcode"],
                    "cds-netskope-destination-ip": ["dstip"],
                    "cds-netskope-destination-port": ["dstport"],
                    "cds-netskope-host-name": ["hostname"],
                    "cds-netskope-organization-unit": ["organization_unit"],
                    "cds-netskope-os": ["os"],
                    "cds-netskope-os-version": ["os_version"],
                    "cds-netskope-page": ["page"],
                    "cds-netskope-protocol": ["protocol"],
                    "cds-netskope-site": ["site"],
                    "cds-netskope-source-country": ["src_country"],
                    "cds-netskope-source-location": ["src_location"],
                    "cds-netskope-source-region": ["src_region"],
                    "cds-netskope-source-time": ["src_time"],
                    "cds-netskope-source-timezone": ["src_timezone"],
                    "cds-netskope-source-zipcode": ["src_zipcode"],
                    "cds-netskope-source-ip": ["srcip"],
                    "cds-netskope-traffic-type": ["traffic_type"],
                    "cds-netskope-type": ["type"],
                    "cds-netskope-user-normalized": ["ur_normalized"],
                    "cds-netskope-url": ["url"],
                    "cds-netskope-user": ["user"],
                    "cds-netskope-user-ip": ["userip"],
                    "cds-netskope-ccl": ["ccl"],
                    "cds-netskope-user-generated": ["user_generated"],
                    "timestamp": [],
                },
                "tag_fields": ["connection-id"],
                "log_fields": [
                    "cds-netskope-connection-id",
                    "cds-netskope-client-bytes",
                    "cds-netskope-connection-duration",
                    "cds-netskope-connection-endtime",
                    "cds-netskope-connection-starttime",
                    "cds-netskope-count",
                    "cds-netskope-http-transactions",
                    "cds-netskope-bytes",
                    "cds-netskope-server-bytes",
                    "cds-netskope-access-method",
                    "cds-netskope-app",
                    "cds-netskope-app-category",
                    "cds-netskope-browser",
                    "cds-netskope-browser-version",
                    "cds-netskope-bypass-traffic",
                    "cds-netskope-device",
                    "cds-netskope-domain",
                    "cds-netskope-destination-country",
                    "cds-netskope-destination-location",
                    "cds-netskope-destination-region",
                    "cds-netskope-destination-timezone",
                    "cds-netskope-destination-zipcode",
                    "cds-netskope-destination-ip",
                    "cds-netskope-destination-port",
                    "cds-netskope-host-name",
                    "cds-netskope-organization-unit",
                    "cds-netskope-os",
                    "cds-netskope-os-version",
                    "cds-netskope-page",
                    "cds-netskope-protocol",
                    "cds-netskope-site",
                    "cds-netskope-source-country",
                    "cds-netskope-source-location",
                    "cds-netskope-source-region",
                    "cds-netskope-source-time",
                    "cds-netskope-source-timezone",
                    "cds-netskope-source-zipcode",
                    "cds-netskope-source-ip",
                    "cds-netskope-traffic-type",
                    "cds-netskope-type",
                    "cds-netskope-user-normalized",
                    "cds-netskope-url",
                    "cds-netskope-user",
                    "cds-netskope-user-ip",
                    "cds-netskope-ccl",
                    "cds-netskope-user-generated",
                    "timestamp",
                ],
                "timestamp_field": "timestamp",
            },
            "connection_cci": {
                "type": "metric",
                "event_fields": ["_id", "cci", "timestamp"],
                "alias_fields": {
                    "connection-id": ["_id"],
                    "cci": [],
                    "timestamp": [],
                },
                "tag_fields": ["connection-id"],
                "metric_fields": ["cci"],
                "timestamp_field": "timestamp",
            },
        },
    },
    {
        "type": "infrastructure",
        "dashboard_panels": {
            "infrastructure_details": {
                "type": "log",
                "event_fields": [
                    "_id",
                    "hostname",
                    "metric_name",
                    "metric_true_count",
                    "metric_type",
                    "metric_value",
                    "package_version",
                    "serial",
                    "timestamp",
                ],
                "alias_fields": {
                    "cds-netskope-infrastructure-id": ["_id"],
                    "cds-netskope-metric-name": ["metric_name"],
                    "cds-netskope-metric-true-count": ["metric_true_count"],
                    "cds-netskope-metric-type": ["metric_type"],
                    "cds-netskope-metric-value": ["metric_value"],
                    "cds-netskope-package-version": ["package_version"],
                    "cds-netskope-serial": ["serial"],
                    "timestamp": [],
                },
                "tag_fields": ["cds-netskope-infrastructure-id"],
                "log_fields": [
                    "cds-netskope-infrastructure-id",
                    "cds-netskope-metric-name",
                    "cds-netskope-metric-true-count",
                    "cds-netskope-metric-type",
                    "cds-netskope-metric-value",
                    "cds-netskope-package-version",
                    "cds-netskope-serial",
                    "timestamp",
                ],
                "timestamp_field": "timestamp",
            }
        },
    },
    {
        "type": "network",
        "dashboard_panels": {
            "network_details": {
                "type": "log",
                "event_fields": [
                    "_id",
                    "client_bytes",
                    "client_packets",
                    "count",
                    "numbytes",
                    "server_bytes",
                    "server_packets",
                    "session_duration",
                    "total_packets",
                    "access_method",
                    "app",
                    "appcategory",
                    "ccl",
                    "device",
                    "dst_country",
                    "os",
                    "os_version",
                    "protocol",
                    "site",
                    "src_country",
                    "traffic_type",
                    "type",
                    "ur_normalized",
                    "user",
                    "userip",
                    "organization_unit",
                    "dst_location",
                    "dst_region",
                    "dst_zipcode",
                    "dstip",
                    "dstport",
                    "src_location",
                    "src_region",
                    "src_zipcode",
                    "srcip",
                    "policy",
                    "timestamp",
                ],
                "alias_fields": {
                    "cds-netskope-network-id": ["_id"],
                    "cds-netskope-client-bytes": ["client_bytes"],
                    "cds-netskope-client-packets": ["client_packets"],
                    "cds-netskope-count": ["count"],
                    "cds-netskope-numbytes": ["numbytes"],
                    "cds-netskope-server-bytes": ["server_bytes"],
                    "cds-netskope-server-packets": ["server_packets"],
                    "cds-netskope-session-duration": ["session_duration"],
                    "cds-netskope-total-packets": ["total_packets"],
                    "cds-netskope-access-method": ["access_method"],
                    "cds-netskope-app": ["app"],
                    "cds-netskope-app-category": ["appcategory"],
                    "cds-netskope-ccl": ["ccl"],
                    "cds-netskope-device": ["device"],
                    "cds-netskope-destination-country": ["dst_country"],
                    "cds-netskope-os": ["os"],
                    "cds-netskope-os-version": ["os_version"],
                    "cds-netskope-protocol": ["protocol"],
                    "cds-netskope-site": ["site"],
                    "cds-netskope-source-country": ["src_country"],
                    "cds-netskope-traffic-type": ["traffic_type"],
                    "cds-netskope-type": ["type"],
                    "cds-netskope-user-normalized": ["ur_normalized"],
                    "cds-netskope-user": ["user"],
                    "cds-netskope-user-ip": ["userip"],
                    "cds-netskope-organization-unit": ["organization_unit"],
                    "cds-netskope-destination-location": ["dst_location"],
                    "cds-netskope-destination-region": ["dst_region"],
                    "cds-netskope-destination-zipcode": ["dst_zipcode"],
                    "cds-netskope-destination-ip": ["dstip"],
                    "cds-netskope-destination-port": ["dstport"],
                    "cds-netskope-source-location": ["src_location"],
                    "cds-netskope-source-region": ["src_region"],
                    "cds-netskope-source-zipcode": ["src_zipcode"],
                    "cds-netskope-source-ip": ["srcip"],
                    "cds-netskope-policy": ["policy"],
                    "timestamp": [],
                },
                "tag_fields": ["cds-netskope-network-id"],
                "log_fields": [
                    "cds-netskope-network-id",
                    "cds-netskope-client-bytes",
                    "cds-netskope-client-packets",
                    "cds-netskope-count",
                    "cds-netskope-numbytes",
                    "cds-netskope-server-bytes",
                    "cds-netskope-server-packets",
                    "cds-netskope-session-duration",
                    "cds-netskope-total-packets",
                    "cds-netskope-access-method",
                    "cds-netskope-app",
                    "cds-netskope-app-category",
                    "cds-netskope-ccl",
                    "cds-netskope-device",
                    "cds-netskope-destination-country",
                    "cds-netskope-os",
                    "cds-netskope-os-version",
                    "cds-netskope-protocol",
                    "cds-netskope-site",
                    "cds-netskope-source-country",
                    "cds-netskope-traffic-type",
                    "cds-netskope-type",
                    "cds-netskope-user-normalized",
                    "cds-netskope-user",
                    "cds-netskope-user-ip",
                    "cds-netskope-organization-unit",
                    "cds-netskope-destination-location",
                    "cds-netskope-destination-region",
                    "cds-netskope-destination-zipcode",
                    "cds-netskope-destination-ip",
                    "cds-netskope-destination-port",
                    "cds-netskope-source-location",
                    "cds-netskope-source-region",
                    "cds-netskope-source-zipcode",
                    "cds-netskope-source-ip",
                    "cds-netskope-policy",
                    "timestamp",
                ],
                "timestamp_field": "timestamp",
            },
            "network": {
                "type": "metric",
                "event_fields": [
                    "_id",
                    "client_bytes",
                    "server_bytes",
                    "client_packets",
                    "server_packets",
                    "session_duration",
                    "timestamp",
                ],
                "alias_fields": {
                    "network-id": ["_id"],
                    "client_bytes": [],
                    "server_bytes": [],
                    "client_packets": [],
                    "server_packets": [],
                    "session_duration": [],
                    "timestamp": [],
                },
                "tag_fields": ["network-id"],
                "metric_fields": [
                    "client_bytes",
                    "server_bytes",
                    "client_packets",
                    "server_packets",
                    "session_duration",
                ],
                "timestamp_field": "timestamp",
            },
        },
    },
    {
        "type": "incident",
        "dashboard_panels": {
            "incident_details": {
                "type": "log",
                "event_fields": [
                    "user",
                    "app",
                    "access_method",
                    "site",
                    "activity",
                    "dlp_file",
                    "object_type",
                    "dlp_match_info.dlp_action",
                    "dlp_match_info.dlp_policy",
                    "dlp_match_info.dlp_rules.dlp_rule_severity",
                    "dlp_rule_severity",
                    "src_location",
                    "dst_location",
                    "severity",
                    "status",
                    "assignee",
                    "object_type",
                    "channel",
                    "timestamp",
                    "_id",
                ],
                "alias_fields": {
                    "cds-netskope-incident-id": ["_id"],
                    "cds-netskope-user": ["user"],
                    "cds-netskope-app": ["app"],
                    "cds-netskope-access-method": ["access_method"],
                    "cds-netskope-site": ["site"],
                    "cds-netskope-activity": ["activity"],
                    "cds-netskope-dlp-file": ["dlp_file"],
                    "cds-netskope-object-type": ["object_type"],
                    "cds-netskope-dlp-action": ["dlp_match_info.dlp_action"],
                    "cds-netskope-dlp-policy": ["dlp_match_info.dlp_policy"],
                    "cds-netskope-dlp-rule-severity": ["dlp_match_info.dlp_rules.dlp_rule_severity"],
                    "cds-netskope-source-location": ["src_location"],
                    "cds-netskope-destination-location": ["dst_location"],
                    "cds-netskope-severity": ["severity"],
                    "cds-netskope-status": ["status"],
                    "cds-netskope-assignee": ["assignee"],
                    "cds-netskope-channel": ["channel"],
                    "timestamp": [],
                },
                "tag_fields": ["cds-netskope-incident-id"],
                "log_fields": [
                    "cds-netskope-incident-id",
                    "cds-netskope-user",
                    "cds-netskope-app",
                    "cds-netskope-access-method",
                    "cds-netskope-site",
                    "cds-netskope-activity",
                    "cds-netskope-dlp-file",
                    "cds-netskope-object-type",
                    "cds-netskope-dlp-action",
                    "cds-netskope-dlp-policy",
                    "cds-netskope-dlp-rule-severity",
                    "cds-netskope-source-location",
                    "cds-netskope-destination-location",
                    "cds-netskope-severity",
                    "cds-netskope-status",
                    "cds-netskope-assignee",
                    "cds-netskope-channel",
                    "timestamp",
                ],
                "timestamp_field": "timestamp",
            },
        },
    },
]
