api_list = [
    {
        "url": "api/datacenter/cluster/clusters",
        "dashboard_panels": {
            "cluster_storage_details": {
                "type": "metric",
                "event_fields": [
                    "name",
                    "uuid",
                    "location",
                    "models",
                    "isSanOptimized",
                    "storage_capacity.used",
                    "storage_capacity.total",
                    "storage_capacity.available",
                ],
                "alias_fields": {
                    "name": [],
                    "uuid": [],
                    "location": [],
                    "models": [],
                    "is-san-optimized": ["isSanOptimized"],
                    "storage-used": ["storage_capacity.used"],
                    "storage-total": ["storage_capacity.total"],
                    "storage-available": ["storage_capacity.available"],
                },
                "tag_fields": [
                    "name",
                    "uuid",
                    "location",
                    "models",
                    "is-san-optimized",
                ],
                "metric_fields": ["storage-used", "storage-total", "storage-available"],
                "custom_metric_tags": {
                    "storage-used": ("storage", ["size-type:used"]),
                    "storage-available": ("storage", ["size-type:available"]),
                },
                "distinct_count": "uuid",
            },
        },
    },
    {
        "url": "api/datacenter/cluster/clusters/analytics",
        "dashboard_panels": {
            "cluster_performance_details": {
                "type": "metric",
                "event_fields": ["throughput", "period", "iops", "cluster.name", "cluster.uuid"],
                "alias_fields": {
                    "throughput": [],
                    "period": [],
                    "iops": [],
                    "cluster-name": ["cluster.name"],
                    "cluster-uuid": ["cluster.uuid"],
                },
                "tag_fields": ["cluster-name", "cluster-uuid"],
                "metric_fields": ["throughput", "period", "iops"],
            }
        },
    },
    {
        "url": "api/datacenter/cluster/nodes",
        "dashboard_panels": {
            "cluster_node_details": {
                "type": "metric",
                "event_fields": [
                    "performance_capacity.used",
                    "uptime",
                    "health",
                    "name",
                    "uuid",
                    "model",
                    "location",
                    "system_id",
                    "serial_number",
                ],
                "alias_fields": {
                    "performance-capacity-used": ["performance_capacity.used"],
                    "uptime": [],
                    "health": [],
                    "name": [],
                    "uuid": [],
                    "model": [],
                    "location": [],
                    "system-id": ["system_id"],
                    "serial-number": ["serial_number"],
                },
                "tag_fields": ["health", "name", "uuid", "model", "location", "system-id", "serial-number"],
                "metric_fields": ["performance-capacity-used", "uptime"],
            },
        },
    },
    {
        "url": "api/datacenter/cluster/licensing/licenses",
        "dashboard_panels": {
            "cluster_licensing_details": {
                "type": "log",
                "event_fields": ["cluster.name", "node.name", "name", "scope", "uuid"],
                "alias_fields": {
                    "cluster-name": ["cluster.name"],
                    "node-name": ["node.name"],
                    "name": [],
                    "scope": [],
                    "uuid": [],
                },
                "log_fields": ["cluster-name", "node-name", "name", "scope"],
                "tag_fields": ["uuid"],
            }
        },
    },
    {
        "url": "api/datacenter/storage/volumes",
        "dashboard_panels": {
            "volume_storage_details": {
                "type": "metric",
                "event_fields": [
                    "space.available",
                    "space.used",
                    "space.size",
                    "name",
                    "uuid",
                    "cluster.name",
                    "type",
                    "state",
                    "svm.name",
                    "create_time",
                ],
                "alias_fields": {
                    "space-available": ["space.available"],
                    "space-used": ["space.used"],
                    "space-size": ["space.size"],
                    "name": [],
                    "uuid": [],
                    "cluster.name": [],
                    "type": [],
                    "volume-state": ["state"],
                    "svm.name": [],
                    "create_time": [],
                },
                "tag_fields": [
                    "name",
                    "uuid",
                    "cluster.name",
                    "type",
                    "volume-state",
                    "svm.name",
                    "create_time",
                ],
                "metric_fields": ["space-available", "space-used", "space-size"],
                "custom_metric_tags": {
                    "space-used": ("space", ["size-type:used"]),
                    "space-available": ("space", ["size-type:available"]),
                },
                "distinct_count": "uuid",
            }
        },
    },
    {
        "url": "/api/datacenter/storage/volumes/analytics",
        "dashboard_panels": {
            "volume_performance_details": {
                "type": "metric",
                "event_fields": [
                    "iops",
                    "latency",
                    "throughput",
                    "volume.name",
                    "volume.uuid",
                    "cluster.name",
                    "svm.name",
                ],
                "alias_fields": {
                    "iops": [],
                    "latency": [],
                    "throughput": [],
                    "volume-name": ["volume.name"],
                    "volume-uuid": ["volume.uuid"],
                    "cluster-name": ["cluster.name"],
                    "svm-name": ["svm.name"],
                },
                "tag_fields": ["volume-name", "volume-uuid", "cluster-name", "svm-name"],
                "metric_fields": ["iops", "latency", "throughput"],
            }
        },
    },
    {
        "url": "/api/datacenter/storage/luns",
        "dashboard_panels": {
            "lun_storage_details": {
                "type": "metric",
                "event_fields": [
                    "space.size",
                    "space.used",
                    "name",
                    "uuid",
                    "cluster.name",
                    "svm.name",
                    "class",
                    "serial_number",
                    "location.qtree.name",
                    "location.volume.name",
                    "os_type",
                    "status.state",
                ],
                "alias_fields": {
                    "space-size": ["space.size"],
                    "space-used": ["space.used"],
                    "name": [],
                    "uuid": [],
                    "cluster-name": ["cluster.name"],
                    "svm-name": ["svm.name"],
                    "class": [],
                    "serial-number": ["serial_number"],
                    "location-qtree-name": ["location.qtree.name"],
                    "location-volume-name": ["location.volume.name"],
                    "os-type": ["os_type"],
                    "lun-status": ["status.state"],
                },
                "tag_fields": [
                    "name",
                    "uuid",
                    "cluster-name",
                    "svm-name",
                    "class",
                    "serial-number",
                    "location-qtree-name",
                    "location-volume-name",
                    "os-type",
                    "lun-status",
                ],
                "metric_fields": [
                    "space-size",
                    "space-used",
                ],
                "distinct_count": "uuid",
            }
        },
    },
    {
        "url": "/api/datacenter/storage/luns/analytics",
        "dashboard_panels": {
            "lun_performance_details": {
                "type": "metric",
                "event_fields": [
                    "iops",
                    "latency",
                    "throughput",
                    "cluster.name",
                    "svm.name",
                    "volume.name",
                    "lun.name",
                    "lun.uuid",
                ],
                "alias_fields": {
                    "iops": [],
                    "latency": [],
                    "throughput": [],
                    "cluster-name": ["cluster.name"],
                    "svm-name": ["svm.name"],
                    "volume-name": ["volume.name"],
                    "lun-name": ["lun.name"],
                    "lun-uuid": ["lun.uuid"],
                },
                "tag_fields": ["cluster-name", "svm-name", "volume-name", "lun-name", "lun-uuid"],
                "metric_fields": [
                    "iops",
                    "latency",
                    "throughput",
                ],
            }
        },
    },
    {
        "url": "/api/datacenter/storage/aggregates",
        "dashboard_panels": {
            "aggregate_details": {
                "type": "metric",
                "event_fields": [
                    "space.block_storage.available",
                    "space.block_storage.size",
                    "space.block_storage.used",
                    "space.efficiency.logical_used",
                    "space.efficiency.savings",
                    "performance_capacity.used",
                    "name",
                    "uuid",
                    "cluster.name",
                    "node.name",
                    "state",
                    "snaplock_type",
                    "type",
                    "create_time",
                ],
                "alias_fields": {
                    "space-block-storage-available": ["space.block_storage.available"],
                    "space-block-storage-size": ["space.block_storage.size"],
                    "space-block-storage-used": ["space.block_storage.used"],
                    "space-efficiency-logical-used": ["space.efficiency.logical_used"],
                    "space-efficiency-savings": ["space.efficiency.savings"],
                    "performance-capacity-used": ["performance_capacity.used"],
                    "name": [],
                    "uuid": [],
                    "cluster-name": ["cluster.name"],
                    "node-name": ["node.name"],
                    "aggregate-state": ["state"],
                    "snaplock-type": ["snaplock_type"],
                    "type": [],
                    "create-time": ["create_time"],
                },
                "tag_fields": [
                    "name",
                    "uuid",
                    "cluster-name",
                    "node-name",
                    "aggregate-state",
                    "snaplock-type",
                    "type",
                    "create-time",
                ],
                "metric_fields": [
                    "space-block-storage-available",
                    "space-block-storage-size",
                    "space-block-storage-used",
                    "space-efficiency-logical-used",
                    "space-efficiency-savings",
                    "performance-capacity-used",
                ],
                "custom_metric_tags": {
                    "space-block-storage-available": ("space-block-storage", ["size-type:available"]),
                    "space-block-storage-used": ("space-block-storage", ["size-type:used"]),
                },
                "distinct_count": "uuid",
            },
            "aggregate_raid_details": {
                "type": "metric",
                "event_fields": [
                    "name",
                    "uuid",
                    "state",
                    "block_storage.primary.raid_type",
                    "block_storage.primary.raid_size",
                ],
                "alias_fields": {
                    "name": [],
                    "uuid": [],
                    "aggregate-raid-state": ["state"],
                    "block-storage-primary-raid-type": ["block_storage.primary.raid_type"],
                    "block-storage-primary-raid-size": ["block_storage.primary.raid_size"],
                },
                "tag_fields": ["name", "uuid", "aggregate-raid-state", "block-storage-primary-raid-type"],
                "metric_fields": ["block-storage-primary-raid-size"],
            },
        },
    },
    {
        "url": "/api/datacenter/storage/aggregates/analytics",
        "dashboard_panels": {
            "aggregate_performance_details": {
                "type": "metric",
                "event_fields": [
                    "iops",
                    "latency",
                    "throughput",
                    "utilization_percent",
                    "performance_capacity.used_percent",
                    "performance_capacity.available_iops_percent",
                    "aggregate.uuid",
                    "aggregate.name",
                    "cluster.name",
                    "node.name",
                ],
                "alias_fields": {
                    "iops": [],
                    "latency": [],
                    "throughput": [],
                    "utilization-percent": ["utilization_percent"],
                    "performance-capacity-used-percent": ["performance_capacity.used_percent"],
                    "performance-capacity-available-iops-percent": ["performance_capacity.available_iops_percent"],
                    "uuid": ["aggregate.uuid"],
                    "name": ["aggregate.name"],
                    "cluster-name": ["cluster.name"],
                    "node-name": ["node.name"],
                },
                "tag_fields": ["name", "uuid", "cluster-name", "node-name"],
                "metric_fields": [
                    "iops",
                    "latency",
                    "throughput",
                    "utilization-percent",
                    "performance-capacity-used-percent",
                    "performance-capacity-available-iops-percent",
                ],
            }
        },
    },
    {
        "url": "/api/datacenter/network/ip/interfaces",
        "dashboard_panels": {
            "ip_interface_details": {
                "type": "log",
                "event_fields": [
                    "name",
                    "uuid",
                    "cluster.name",
                    "ipspace.name",
                    "svm.name",
                    "ip.address",
                    "ip.netmask",
                    "ip.family",
                    "location.failover",
                    "location.node.name",
                    "location.port.name",
                    "location.is_home",
                    "scope",
                    "state",
                    "enabled",
                ],
                "alias_fields": {
                    "name": [],
                    "uuid": [],
                    "cluster-name": ["cluster.name"],
                    "ipspace-name": ["ipspace.name"],
                    "svm-name": ["svm.name"],
                    "ip-address": ["ip.address"],
                    "ip-netmask": ["ip.netmask"],
                    "ip-family": ["ip.family"],
                    "location-failover": ["location.failover"],
                    "location-node-name": ["location.node.name"],
                    "location-port-name": ["location.port.name"],
                    "location-is-home": ["location.is_home"],
                    "scope": [],
                    "interface-state": ["state"],
                    "enabled": [],
                },
                "tag_fields": ["uuid"],
                "log_fields": [
                    "name",
                    "cluster-name",
                    "ipspace-name",
                    "svm-name",
                    "ip-address",
                    "ip-netmask",
                    "ip-family",
                    "location-failover",
                    "location-node-name",
                    "location-port-name",
                    "location-is-home",
                    "scope",
                    "interface-state",
                    "enabled",
                ],
            }
        },
    },
    {
        "url": "/api/datacenter/network/ip/interfaces/analytics",
        "dashboard_panels": {
            "ip_interface_performance_details": {
                "type": "metric",
                "event_fields": [
                    "iops",
                    "latency",
                    "throughput",
                    "svm.name",
                    "cluster.name",
                    "ip_interface.name",
                    "ip_interface.uuid",
                ],
                "alias_fields": {
                    "iops": [],
                    "latency": [],
                    "throughput": [],
                    "svm-name": ["svm.name"],
                    "cluster-name": ["cluster.name"],
                    "name": ["ip_interface.name"],
                    "uuid": ["ip_interface.uuid"],
                },
                "tag_fields": ["svm-name", "cluster-name", "name", "uuid"],
                "metric_fields": ["iops", "latency", "throughput"],
            }
        },
    },
    {
        "url": "/api/datacenter/network/ethernet/ports",
        "dashboard_panels": {
            "ethernet_port_details": {
                "type": "log",
                "event_fields": [
                    "name",
                    "uuid",
                    "enabled",
                    "speed",
                    "type",
                    "state",
                    "cluster.name",
                    "node.name",
                    "broadcast_domain.name",
                    "mac_address",
                ],
                "alias_fields": {
                    "name": [],
                    "uuid": [],
                    "enabled": [],
                    "speed": [],
                    "port-type": ["type"],
                    "port-state": ["state"],
                    "cluster-name": ["cluster.name"],
                    "node-name": ["node.name"],
                    "broadcast-domain-name": ["broadcast_domain.name"],
                    "mac-address": ["mac_address"],
                },
                "tag_fields": ["uuid"],
                "log_fields": [
                    "name",
                    "enabled",
                    "speed",
                    "port-type",
                    "port-state",
                    "cluster-name",
                    "node-name",
                    "broadcast-domain-name",
                    "mac-address",
                ],
            }
        },
    },
    {
        "url": "/api/datacenter/network/ethernet/ports/analytics",
        "dashboard_panels": {
            "ethernet_port_performance_details": {
                "type": "metric",
                "event_fields": [
                    "node.name",
                    "cluster.name",
                    "ethernet_port.name",
                    "ethernet_port.uuid",
                    "throughput",
                    "utilization_percent",
                ],
                "alias_fields": {
                    "node-name": ["node.name"],
                    "cluster-name": ["cluster.name"],
                    "name": ["ethernet_port.name"],
                    "uuid": ["ethernet_port.uuid"],
                    "throughput": [],
                    "utilization-percent": ["utilization_percent"],
                },
                "tag_fields": [
                    "node-name",
                    "cluster-name",
                    "name",
                    "uuid",
                ],
                "metric_fields": [
                    "throughput",
                    "utilization-percent",
                ],
                "distinct_count": "ethernet-port-uuid",
            }
        },
    },
    {
        "url": "/api/datacenter/network/fc/ports",
        "dashboard_panels": {
            "fibre_channel_ports_detail": {
                "type": "metric",
                "event_fields": [
                    "fabric.connected_speed",
                    "name",
                    "uuid",
                    "cluster.name",
                    "node.name",
                    "enabled",
                    "state",
                    "fabric.connected",
                    "physical_protocol",
                ],
                "alias_fields": {
                    "fabric-connected-speed": ["fabric.connected_speed"],
                    "name": [],
                    "uuid": [],
                    "cluster-name": ["cluster.name"],
                    "node-name": ["node.name"],
                    "enabled": [],
                    "port-state": ["state"],
                    "fabric-connected": ["fabric.connected"],
                    "physical-protocol": ["physical_protocol"],
                },
                "tag_fields": [
                    "name",
                    "uuid",
                    "cluster-name",
                    "node-name",
                    "enabled",
                    "port-state",
                    "fabric-connected",
                    "physical-protocol",
                ],
                "metric_fields": [
                    "fabric-connected-speed",
                ],
                "distinct_count": "uuid",
            }
        },
    },
    {
        "url": "/api/datacenter/network/fc/ports/analytics",
        "dashboard_panels": {
            "fibre_channel_ports_performance_details": {
                "type": "metric",
                "event_fields": [
                    "throughput",
                    "utilization_percent",
                    "node.name",
                    "cluster.name",
                    "fc_port.name",
                    "fc_port.uuid",
                ],
                "alias_fields": {
                    "throughput": [],
                    "utilization-percent": ["utilization_percent"],
                    "node-name": ["node.name"],
                    "cluster-name": ["cluster.name"],
                    "name": ["fc_port.name"],
                    "uuid": ["fc_port.uuid"],
                },
                "tag_fields": [
                    "node-name",
                    "cluster-name",
                    "name",
                    "uuid",
                ],
                "metric_fields": [
                    "throughput",
                    "utilization-percent",
                ],
            }
        },
    },
    {
        "url": "/api/datacenter/storage/qtrees",
        "dashboard_panels": {
            "qtree_details": {
                "type": "log",
                "event_fields": [
                    "name",
                    "id",
                    "status",
                    "cluster.name",
                    "svm.name",
                    "volume.name",
                    "security_style",
                    "unix_permissions",
                    "export_policy.name",
                ],
                "alias_fields": {
                    "name": [],
                    "id": [],
                    "qtree-status": ["status"],
                    "cluster-name": ["cluster.name"],
                    "svm-name": ["svm.name"],
                    "volume-name": ["volume.name"],
                    "security-style": ["security_style"],
                    "unix-permissions": ["unix_permissions"],
                    "export-policy-name": ["export_policy.name"],
                },
                "tag_fields": ["id"],
                "log_fields": [
                    "name",
                    "id",
                    "qtree-status",
                    "cluster-name",
                    "svm-name",
                    "volume-name",
                    "security-style",
                    "unix-permissions",
                    "export-policy-name",
                ],
                "conditions": {"id": ["not_empty", "not_zero"]},
            }
        },
    },
]
