schedules:
- cron: 0 5 * * *
  displayName: Nightly (EDT/EST)
  always: true
  branches:
    include:
    - master
pr: none
trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: integrations-core
    type: github
    name: Datadog/integrations-core
    ref: master
    endpoint: DataDog
variables:
  DDEV_COLOR: 1
jobs:
- template: .azure-pipelines/templates/test-all.yml@integrations-core
  parameters:
    repo: marketplace
    coverage: false
    # Each integration needs to be added here to be tested and validated
    checks:
    - checkName: fairwinds_insights
      displayName: Fairwinds Insights
      os: linux
    - checkName: syntheticemail
      displayName: RapDev Synthetic Email
      os: linux
    - checkName: o365
      displayName: RapDev Office 365
      os: linux
