name: Master

on:
  push:
    branches:
    - master

jobs:
  test:
    uses: ./.github/workflows/test-all.yml
    with:
      repo: marketplace

      # Options
      standard: true
    secrets: inherit

  publish-test-results:
    needs:
    - test
    if: success() || failure()
    concurrency:
      group: test-results

    uses: DataDog/integrations-core/.github/workflows/test-results-master.yml@master
    secrets: inherit
