name: Reviewer
on:
- pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependency
      run: |
        pip install PyGithub
      
    - name: Add review labels
      run: python .github/workflows/scripts/reviewer.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
