name: Validate repository

on:
  push:
    branches:
    - master
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  standard:
    uses: DataDog/integrations-core/.github/workflows/run-validations.yml@master
    with:
      repo: marketplace

      # Validations
      ci: true
      codeowners: true
      config: true
      dashboards: true
      eula: true
      imports: true
      integration-style: true
      jmx-metrics: true
      legacy-signature: true
      metadata: true
      models: true
      package: true
      readmes: true
      recommended-monitors: true
      saved-views: true
      service-checks: true
    secrets: inherit
