[env.collectors.datadog-checks]

[[envs.default.matrix]]
python = ["2.7", "3.8"]

[envs.default]
e2e-env = false

[envs.lint.overrides]
platform.linux.scripts = [
  { key = "all", value = "- style" },
]
